### ISSUE TITLE
(BUG )[StudyBuddy-android v1.0.0-rc.543 ]   After opening the application, the application crashes when I click on manual sync.

### ISSUE THREAD

**Issue by XAMIR555** [EdricChan03/StudyBuddy-android#188]
#### Project Information
* Repository-----------:[Here](https://github.com/EdricChan03/StudyBuddy-android)
* Project Name---------:   [StudyBuddy-android](https://github.com/EdricChan03/StudyBuddy-android/releases)
* Publisher------------: [Edric Chan](https://github.com/EdricChan03)
* My GitHub account----:  [Here](https://github.com/XAMIR555)

#### Expected behavior

After I open the application, when I click on manual sync, all the manual sync options should go to OPEN so that users can use them easily.

#### Actual behavior

 After opening the application, the application crashes when I click on manual sync.

#### How to reproduce
* download the latest version of application
* after open the application click on the 3 vertical dots 
*  go to setting option
* select the data sync option and open it 
* click on Manual sync option
* Note the Bug

* Browser/App version-: v1.0.0-rc.543
* Operating system----: 9.0.0

#### Recording Of The Bug

![20190727_185456](https://user-images.githubusercontent.com/49812927/61995337-10545780-b03c-11e9-8efe-ee814351e88b.gif)

# Logcat

<pre><code>07-27 16:48:43.949 16251 16251 E AndroidRuntime: FATAL EXCEPTION: main
07-27 16:48:43.949 16251 16251 E AndroidRuntime: Process: com.edricchan.studybuddy, PID: 16251
07-27 16:48:43.949 16251 16251 E AndroidRuntime: java.lang.RuntimeException: Unable to start activity ComponentInfo{com.edricchan.studybuddy/com.edricchan.studybuddy.MyIntroActivity}: java.lang.ClassCastException: com.edricchan.studybuddy.a.b cannot be cast to com.heinrichreimersoftware.materialintro.b.a
07-27 16:48:43.949 16251 16251 E AndroidRuntime: 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3121)
07-27 16:48:43.949 16251 16251 E AndroidRuntime: 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3264)
07-27 16:48:43.949 16251 16251 E AndroidRuntime: 	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:78)
07-27 16:48:43.949 16251 16251 E AndroidRuntime: 	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108)
07-27 16:48:43.949 16251 16251 E AndroidRuntime: 	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68)
07-27 16:48:43.949 16251 16251 E AndroidRuntime: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1955)
07-27 16:48:43.949 16251 16251 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:106)
07-27 16:48:43.949 16251 16251 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:214)
07-27 16:48:43.949 16251 16251 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:7091)
07-27 16:48:43.949 16251 16251 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
07-27 16:48:43.949 16251 16251 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
07-27 16:48:43.949 16251 16251 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:965)
07-27 16:48:43.949 16251 16251 E AndroidRuntime: Caused by: java.lang.ClassCastException: com.edricchan.studybuddy.a.b cannot be cast to com.heinrichreimersoftware.materialintro.b.a
07-27 16:48:43.949 16251 16251 E AndroidRuntime: 	at com.heinrichreimersoftware.materialintro.a.a.onCreate(Unknown Source:123)
07-27 16:48:43.949 16251 16251 E AndroidRuntime: 	at com.edricchan.studybuddy.MyIntroActivity.onCreate(Unknown Source:0)
07-27 16:48:43.949 16251 16251 E AndroidRuntime: 	at android.app.Activity.performCreate(Activity.java:7327)
07-27 16:48:43.949 16251 16251 E AndroidRuntime: 	at android.app.Activity.performCreate(Activity.java:7318)
07-27 16:48:43.949 16251 16251 E AndroidRuntime: 	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1275)
07-27 16:48:43.949 16251 16251 E AndroidRuntime: 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3101)
07-27 16:48:43.949 16251 16251 E AndroidRuntime: 	... 11 more
07-27 16:49:09.537 16438 16438 E AndroidRuntime: FATAL EXCEPTION: main
07-27 16:49:09.537 16438 16438 E AndroidRuntime: Process: com.edricchan.studybuddy, PID: 16438
07-27 16:49:09.537 16438 16438 E AndroidRuntime: java.lang.ArrayIndexOutOfBoundsException: length=2; index=10
07-27 16:49:09.537 16438 16438 E AndroidRuntime: 	at com.crashlytics.android.c.j.a(Unknown Source:5)
07-27 16:49:09.537 16438 16438 E AndroidRuntime: 	at com.crashlytics.android.c.m.f(Unknown Source:5)
07-27 16:49:09.537 16438 16438 E AndroidRuntime: 	at com.crashlytics.android.a.f(Unknown Source:2)
07-27 16:49:09.537 16438 16438 E AndroidRuntime: 	at com.edricchan.studybuddy.SettingsActivity$DataSyncPreferenceFragment$1.onPreferenceClick(Unknown Source:4)
07-27 16:49:09.537 16438 16438 E AndroidRuntime: 	at android.preference.Preference.performClick(Preference.java:1250)
07-27 16:49:09.537 16438 16438 E AndroidRuntime: 	at android.preference.PreferenceScreen.onItemClick(PreferenceScreen.java:262)
07-27 16:49:09.537 16438 16438 E AndroidRuntime: 	at android.widget.AdapterView.performItemClick(AdapterView.java:362)
07-27 16:49:09.537 16438 16438 E AndroidRuntime: 	at android.widget.AbsListView.performItemClick(AbsListView.java:1689)
07-27 16:49:09.537 16438 16438 E AndroidRuntime: 	at android.widget.AbsListView$PerformClick.run(AbsListView.java:4130)
07-27 16:49:09.537 16438 16438 E AndroidRuntime: 	at android.widget.AbsListView$7.run(AbsListView.java:6612)
07-27 16:49:09.537 16438 16438 E AndroidRuntime: 	at android.os.Handler.handleCallback(Handler.java:873)
07-27 16:49:09.537 16438 16438 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:99)
07-27 16:49:09.537 16438 16438 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:214)
07-27 16:49:09.537 16438 16438 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:7091)
07-27 16:49:09.537 16438 16438 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
07-27 16:49:09.537 16438 16438 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
07-27 16:49:09.537 16438 16438 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:965)
07-27 16:49:19.848 16801 16801 E AndroidRuntime: FATAL EXCEPTION: main
07-27 16:49:19.848 16801 16801 E AndroidRuntime: Process: com.edricchan.studybuddy, PID: 16801
07-27 16:49:19.848 16801 16801 E AndroidRuntime: java.lang.ArrayIndexOutOfBoundsException: length=2; index=10
07-27 16:49:19.848 16801 16801 E AndroidRuntime: 	at com.crashlytics.android.c.j.a(Unknown Source:5)
07-27 16:49:19.848 16801 16801 E AndroidRuntime: 	at com.crashlytics.android.c.m.f(Unknown Source:5)
07-27 16:49:19.848 16801 16801 E AndroidRuntime: 	at com.crashlytics.android.a.f(Unknown Source:2)
07-27 16:49:19.848 16801 16801 E AndroidRuntime: 	at com.edricchan.studybuddy.SettingsActivity$DataSyncPreferenceFragment$1.onPreferenceClick(Unknown Source:4)
07-27 16:49:19.848 16801 16801 E AndroidRuntime: 	at android.preference.Preference.performClick(Preference.java:1250)
07-27 16:49:19.848 16801 16801 E AndroidRuntime: 	at android.preference.PreferenceScreen.onItemClick(PreferenceScreen.java:262)
07-27 16:49:19.848 16801 16801 E AndroidRuntime: 	at android.widget.AdapterView.performItemClick(AdapterView.java:362)
07-27 16:49:19.848 16801 16801 E AndroidRuntime: 	at android.widget.AbsListView.performItemClick(AbsListView.java:1689)
07-27 16:49:19.848 16801 16801 E AndroidRuntime: 	at android.widget.AbsListView$PerformClick.run(AbsListView.java:4130)
07-27 16:49:19.848 16801 16801 E AndroidRuntime: 	at android.widget.AbsListView$7.run(AbsListView.java:6612)
07-27 16:49:19.848 16801 16801 E AndroidRuntime: 	at android.os.Handler.handleCallback(Handler.java:873)
07-27 16:49:19.848 16801 16801 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:99)
07-27 16:49:19.848 16801 16801 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:214)
07-27 16:49:19.848 16801 16801 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:7091)
07-27 16:49:19.848 16801 16801 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
07-27 16:49:19.848 16801 16801 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
07-27 16:49:19.848 16801 16801 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:965)
07-27 16:50:17.542 16889 16889 E AndroidRuntime: FATAL EXCEPTION: main
07-27 16:50:17.542 16889 16889 E AndroidRuntime: Process: com.edricchan.studybuddy, PID: 16889
07-27 16:50:17.542 16889 16889 E AndroidRuntime: java.lang.ArrayIndexOutOfBoundsException: length=2; index=10
07-27 16:50:17.542 16889 16889 E AndroidRuntime: 	at com.crashlytics.android.c.j.a(Unknown Source:5)
07-27 16:50:17.542 16889 16889 E AndroidRuntime: 	at com.crashlytics.android.c.m.f(Unknown Source:5)
07-27 16:50:17.542 16889 16889 E AndroidRuntime: 	at com.crashlytics.android.a.f(Unknown Source:2)
07-27 16:50:17.542 16889 16889 E AndroidRuntime: 	at com.edricchan.studybuddy.SettingsActivity$DataSyncPreferenceFragment$1.onPreferenceClick(Unknown Source:4)
07-27 16:50:17.542 16889 16889 E AndroidRuntime: 	at android.preference.Preference.performClick(Preference.java:1250)
07-27 16:50:17.542 16889 16889 E AndroidRuntime: 	at android.preference.PreferenceScreen.onItemClick(PreferenceScreen.java:262)
07-27 16:50:17.542 16889 16889 E AndroidRuntime: 	at android.widget.AdapterView.performItemClick(AdapterView.java:362)
07-27 16:50:17.542 16889 16889 E AndroidRuntime: 	at android.widget.AbsListView.performItemClick(AbsListView.java:1689)
07-27 16:50:17.542 16889 16889 E AndroidRuntime: 	at android.widget.AbsListView$PerformClick.run(AbsListView.java:4130)
07-27 16:50:17.542 16889 16889 E AndroidRuntime: 	at android.widget.AbsListView$7.run(AbsListView.java:6612)
07-27 16:50:17.542 16889 16889 E AndroidRuntime: 	at android.os.Handler.handleCallback(Handler.java:873)
07-27 16:50:17.542 16889 16889 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:99)
07-27 16:50:17.542 16889 16889 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:214)
07-27 16:50:17.542 16889 16889 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:7091)
07-27 16:50:17.542 16889 16889 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
</code></pre>

**Comment by EdricChan03** [comment]
Hi there! Nice to see that you've used my app.

Just saying that the manual sync preference was not meant to be implemented and will be removed in a future release. (I should've removed the preference instead of setting the preference to intentionally crash the app)

I'm closing this issue. If you've any more queries about the app, feel free to post here.

**Comment by EdricChan03** [comment]
Hey @XAMIR555, are you sure you've posted the right stack trace? I don't think that's the actual stack trace when you click on the preference - the stack trace you've posted doesn't seem relevant to what the preference would actually do.
